#Default dir of steam version of desperados, you can change it if you have a different version or want to use it with a different path
exeName=desperados.exe
gameDir=C\:\\Program Files (x86)\\Steam\\steamapps\\common\\Desperados Wanted Dead or Alive
